export const storeMovies = [
  {
    id: 1,
    title: "Spider-Man: No Way Home (2021)",
    rating: "unavailable",
    img: "img/spiderman.jpg",
    info: "For the first time in the cinematic history of Spider-Man, our friendly neighborhood hero is unmasked and no longer able to separate his normal life from the high-stakes of being a Super Hero. When he asks for help from Doctor Strange, the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
    watchlist: false,
    Director: "Jon Watts",
    Stars: "Zendaya, Tom Holland, Alfred Molina, Marisa Tomei",
  },
  {
    id: 2,
    title: " Reminiscence (2021)",
    rating: "5.9",
    img: "img/reminiscence.jpg",
    info: "Nick Bannister, a private investigator of the mind, navigates the alluring world of the past when his life is changed by new client Mae. A simple case becomes an obsession after she disappears and he fights to learn the truth about her.",
    watchlist: false,
    Director: "Lisa Joy",
    Stars: " Hugh Jackman, Rebecca Ferguson, Thandiwe Newton, Cliff Curtis",
  },
  {
    id: 3,
    title: " Sweet Girl (2021)",
    rating: "5.5",
    img: "img/sweetgirl.jpg",
    info: "A devastated husband vows to bring justice to the people responsible for his wife's death while protecting the only family he has left, his daughter.",
    watchlist: false,
    Director: "Brian Andrew Mendoza ",
    Stars: "Jason Momoa, Isabela Merced, Manuel Garcia-Rulfo, Adria Arjona",
  },
  {
    id: 4,
    title: " Free Guy (2021)",
    rating: "7.6",
    img: "img/freeguy.jpg",
    info: "A bank teller discovers that he's actually an NPC inside a brutal, open world video game.",
    watchlist: false,
    Director: "Shawn Levy",
    Stars: " Ryan Reynolds, Jodie Comer, Taika Waititi, Lil Rel Howery",
  },
  {
    id: 5,
    title: "The Suicide Squad (2021)",
    rating: "7.4",
    img: "img/squad.jpg",
    info: "Supervillains Harley Quinn, Bloodsport, Peacemaker and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese.",
    watchlist: false,
    Director: "James Gunn",
    Stars: "Margot Robbie, Idris Elba, John Cena, Joel Kinnaman",
  },
  {
    id: 6,
    title: "The Green Knight (2021)",
    rating: "6.7",
    img: "img/knight.jpg",
    info: "A fantasy re-telling of the medieval story of Sir Gawain and the Green Knight.",
    watchlist: false,
    Director: "David Lowery",
    Stars: "Dev Patel, Alicia Vikander, Joel Edgerton, Sarita",
  },
  {
    id: 7,
    title: " Eternals (2021)",
    rating: "unavailable",
    img: "img/eternals.jpg",
    info: "The saga of the Eternals, a race of immortal beings who lived on Earth and shaped its history and civilizations.",
    watchlist: false,
    Director: "Chloé Zhao",
    Stars: "Salma Hayek, Angelina Jolie, Richard Madden, Kit Harington",
  },
  {
    id: 8,
    title: "Candyman (2021)",
    rating: "6.4",
    img: "img/candy.jpg",
    info: "A sequel to the horror film Candyman (1992) that returns to the now-gentrified Chicago neighborhood where the legend began.",
    watchlist: false,
    Director: "Nia DaCosta",
    Stars:
      "Yahya Abdul-Mateen II, Teyonah Parris, Nathan Stewart-Jarrett, Colman Domingo",
  },
];

export const detailMovie = {
  id: 1,
  title: "Spider-Man: No Way Home (2021)",
  rating: "unavailable",
  img: "img/spiderman.jpg",
  info: "For the first time in the cinematic history of Spider-Man, our friendly neighborhood hero is unmasked and no longer able to separate his normal life from the high-stakes of being a Super Hero. When he asks for help from Doctor Strange, the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
  watchlist: false,
  Director: "Jon Watts",
  Stars: "Zendaya, Tom Holland, Alfred Molina, Marisa Tomei",
};
